apiVersion: v1
kind: Secret
metadata:
  name: control-plane-secret
  namespace: development
type: Opaque
stringData:
  AUTH_SECRET: "{{AUTH_SECRET}}"
  CONTROL_PLANE_GITHUB_ORGS: "{{CONTROL_PLANE_GITHUB_ORGS}}"
  DB_CONTROL_PLANE: "{{DB_CONTROL_PLANE}}"
  CLICKUP_BASE_URL: "{{CLICKUP_BASE_URL}}"
  CLICKUP_PERSONAL_TOKEN_SUPPORT: "{{CLICKUP_PERSONAL_TOKEN_SUPPORT}}"
  CLICKUP_PERSONAL_TOKEN_ELRA: "{{CLICKUP_PERSONAL_TOKEN_ELRA}}"
  CLICKUP_WORKSPACE_ID: "{{CLICKUP_WORKSPACE_ID}}"
  CLICKUP_CHANNEL_ID: "{{CLICKUP_CHANNEL_ID}}"
  CLICKUP_SIGNOFF_SPRINT_FOLDER_ID: "{{CLICKUP_SIGNOFF_SPRINT_FOLDER_ID}}"
  CLICKUP_SIGNOFF_DOCS_FOLDER_ID: "{{CLICKUP_SIGNOFF_DOCS_FOLDER_ID}}"
  CLICKUP_SIGNOFF_ASSIGNEE_IDS: "{{CLICKUP_SIGNOFF_ASSIGNEE_IDS}}"
