apiVersion: v1
kind: Service
metadata:
  name: control-plane-service-int
  namespace: development
spec:
  type: NodePort
  selector:
    app: control-plane-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
